accounts/models.py
# -*- coding: utf-8 -*-
from werkzeug.security import generate_password_hash, check_password_hash
from flask import current_app

from datetime import datetime
from application import db
from common.models import BaseDocument


class User(BaseDocument):

    username = db.StringField(
        verbose_name=u'login',
        max_length=30,
        required=True,
        unique=True
    )

    name = db.StringField(
        verbose_name=u'nome',
        max_length=100
    )

    email = db.EmailField(
        verbose_name=u'e-mail',
        max_length=100,
        required=True,
        unique=True
    )

    pw_hash = db.StringField(
        verbose_name=u'senha',
        max_length=100,
        required=True
    )

    is_active = db.BooleanField(
        verbose_name=u'ativo',
        default=True,
        required=True
    )

    is_superuser = db.BooleanField(
        verbose_name=u'super usuário',
        default=False,
        required=True
    )

    last_login = db.DateTimeField(
        verbose_name=u'último login',
        required=False
    )

    meta = {
        'indexes': ['username', 'email']
    }

    def __unicode__(self):
        return self.username

    def __init__(self, *args, **kwargs):
        password = kwargs.pop('password', None)
        super(User, self).__init__(*args, **kwargs)
        if password:
            self.set_password(password)

    def set_password(self, password):
        self.pw_hash = generate_password_hash(
            password, method=current_app.config['PROJECT_PASSWORD_HASH_METHOD']
        )

    def check_password(self, password):
        return check_password_hash(self.pw_hash, password)

    def refresh_last_login(self):
        self.last_login = datetime.now()
        self.save()

accounts/forms.py
# -*- coding: utf-8 -*-
from flask import render_template, current_app
from wtforms import *
from flask.ext.wtf import Form
from flask_mail import Message

from application import mail
from common.utils import get_signer
from accounts.models import User


class LoginForm(Form):

    user = None

    username = TextField(
        label=u'Login',
        validators=[
            validators.required()
        ]
    )

    password = PasswordField(
        label=u'Password',
        validators=[
            validators.required()
        ]
    )

    next = HiddenField()

    def validate_username(form, field):
        username = field.data
        try:
            form.user = User.objects.get(username=username)
        except:
            raise ValidationError(u'Login not found.')

    def validate_password(form, field):
        password = field.data
        if form.user:
            if not form.user.check_password(password):
                raise ValidationError(u'Incorrect password.')


class SignupForm(Form):

    email = TextField(
        label=u'E-mail',
        validators=[
            validators.required(),
            validators.length(max=100),
            validators.Email()
        ]
    )

    def validate_email(form, field):
        email = field.data
        if User.objects.filter(email=email):
            raise ValidationError(u'E-mail in use.')

    def save(self):
        email = self.email.data
        site_name = current_app.config['PROJECT_SITE_NAME']
        site_url = current_app.config['PROJECT_SITE_URL']
        sender = current_app.config['MAIL_DEFAULT_SENDER']

        # create signed data
        s = get_signer()
        data = {
            'email': email,
            'signup': True
        }
        signed_data = s.dumps(data)

        # set context to template render
        context = dict(
            site_name=site_name,
            site_url=site_url,
            email=email,
            signed_data=signed_data
        )

        # load template
        html = render_template(
            'accounts/emails/signup.html', **context
        )

        # create and send message
        msg = Message(
            u'Confirm your account - {0}.'.format(site_name),
            sender=sender,
            recipients=[email]
        )
        msg.html = html
        mail.send(msg)


class SignupConfirmForm(Form):

    name = TextField(
        label=u'Name',
        validators=[
            validators.required(),
            validators.length(max=100)
        ]
    )

    username = TextField(
        label=u'Login',
        validators=[
            validators.required(),
            validators.length(min=3, max=30),
            validators.Regexp(
                regex=r'^[\w]+$',
                message=u'Just letters and numbers.'
            )
        ]
    )

    password = PasswordField(
        label=u'Password',
        validators=[
            validators.required(),
            validators.length(min=6, max=16)
        ]
    )

    password_confirm = PasswordField(
        label=u'Password Confirm',
        validators=[
            validators.required()
        ]
    )

    next = HiddenField()

    def validate_username(form, field):
        username = field.data
        if User.objects.filter(username=username):
            raise ValidationError(u'Login in use.')

    def validate_password_confirm(form, field):
        password = form.password.data
        password_confirm = field.data
        if password != password_confirm:
            raise ValidationError(u'Incorrect password.')

    def save(self, email):
        name = self.name.data
        username = self.username.data
        password = self.password.data
        email = email

        user = User(name=name, username=username, password=password, email=email)
        user.save()
        return user


class RecoverPasswordForm(Form):

    email = TextField(
        label=u'E-mail',
        validators=[
            validators.required(),
            validators.length(max=100),
            validators.Email()
        ]
    )

    def validate_email(form, field):
        email = field.data
        if not User.objects.filter(email=email):
            raise ValidationError(u'E-mail not found.')

    def save(self):
        email = self.email.data
        site_name = current_app.config['PROJECT_SITE_NAME']
        site_url = current_app.config['PROJECT_SITE_URL']
        sender = current_app.config['MAIL_DEFAULT_SENDER']

        # create signed data
        s = get_signer()
        data = {
            'email': email,
            'recover-password': True
        }
        signed_data = s.dumps(data)

        # set context to template render
        context = dict(
            site_name=site_name,
            site_url=site_url,
            email=email,
            signed_data=signed_data
        )

        # load template
        html = render_template(
            'accounts/emails/recover_password.html', **context
        )

        # create and send message
        msg = Message(
            u'Recover your password - {0}.'.format(site_name),
            sender=sender,
            recipients=[email]
        )
        msg.html = html
        mail.send(msg)


class RecoverPasswordConfirmForm(Form):

    password = PasswordField(
        label=u'Password',
        validators=[
            validators.required(),
            validators.length(min=6, max=16)
        ]
    )

    password_confirm = PasswordField(
        label=u'Password Confirm',
        validators=[
            validators.required()
        ]
    )

    def validate_password_confirm(form, field):
        password = form.password.data
        password_confirm = field.data
        if password != password_confirm:
            raise ValidationError(u'Incorrect password.')

    def save(self):
        password = self.password.data
        self.user.set_password(password)
        self.user.save()
        return self.user

accounts/views.py
# -*- coding: utf-8 -*-
from flask import (
    Blueprint, render_template, session, g, flash, request, redirect, url_for,
    current_app
)
from accounts.models import User
from accounts.forms import (
    LoginForm, SignupForm, SignupConfirmForm, RecoverPasswordForm,
    RecoverPasswordConfirmForm
)
from common.utils import get_signer


accounts_app = Blueprint('accounts_app', __name__)


@accounts_app.before_app_request
def load_user():
    g.user = None
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
        except:
            pass


@accounts_app.route('/login/', methods=['GET', 'POST'])
def login():
    next = request.values.get('next', '/')
    form = LoginForm()
    form.next.data = next
    if form.validate_on_submit():
        session['user_id'] = unicode(form.user.pk)
        flash(u'Login successfully', 'success')
        return redirect(next)
    return render_template('accounts/login.html', form=form)


@accounts_app.route('/logout/')
def logout():
    next = request.args.get('next', '/')
    flash(u'Logout successfully', 'success')
    session.pop('user_id', None)
    return redirect(next)


@accounts_app.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        form.save()
        flash(
            u'Check your email to confirm registration.',
            'success'
        )
        return redirect(url_for('pages_app.index'))
    return render_template('accounts/signup.html', form=form)


@accounts_app.route('/signup/<token>/', methods=['GET', 'POST'])
def signup_confirm(token):
    s = get_signer()
    try:
        signed_data = s.loads(
            token, max_age=current_app.config['PROJECT_SIGNUP_TOKEN_MAX_AGE']
        )
        email = signed_data['email']
        signup = signed_data['signup']
    except:
        flash(u'Invalid activation Link.', 'error')
        return redirect(url_for('accounts_app.signup'))

    if User.objects.filter(email=email):
        flash(u'E-mail in use.', 'error')
        return redirect(url_for('accounts_app.signup'))

    next = request.values.get('next', '/')

    form = SignupConfirmForm()
    form.next.data = next
    if form.validate_on_submit():
        user = form.save(email=email)
        session['user_id'] = unicode(user.pk)
        flash(u'Account registered successfully.', 'success')
        return redirect(next)
    return render_template('accounts/signup_confirm.html', form=form, token=token)


@accounts_app.route('/recover-password/', methods=['GET', 'POST'])
def recover_password():
    form = RecoverPasswordForm()
    if form.validate_on_submit():
        form.save()
        flash(
            u'Check it out at your email instructions for setting a new password.',
            'success'
        )
        return redirect(url_for('pages_app.index'))
    return render_template('accounts/recover_password.html', form=form)


@accounts_app.route('/recover-password/<token>/', methods=['GET', 'POST'])
def recover_password_confirm(token):
    s = get_signer()
    try:
        signed_data = s.loads(
            token, max_age=current_app.config['PROJECT_RECOVER_PASSWORD_TOKEN_MAX_AGE']
        )
        email = signed_data['email']
        recover_password = signed_data['recover-password']
    except:
        flash(u'Invalid Link.', 'error')
        return redirect(url_for('pages_app.index'))

    try:
        user = User.objects.get(email=email)
    except:
        flash(u'E-mail not found.', 'error')
        return redirect(url_for('pages_app.index'))

    form = RecoverPasswordConfirmForm()
    form.user = user
    if form.validate_on_submit():
        user = form.save()
        flash(u'Password set successfully.', 'success')
        return redirect(url_for('accounts_app.login'))
    return render_template(
        'accounts/recover_password_confirm.html',
        form=form, token=token, user=user
    )

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="page-header">
  <h3>Login</h3>
</div>

<form action="{{ url_for('accounts_app.login') }}" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.username, with_label=True) }}
  {{ form_macro.form_field(form.password, with_label=True) }}
  <div class="form-actions">
    <button type="submit" class="btn btn-icon btn-primary">Send</button>
    <a href="{{ url_for('accounts_app.recover_password') }}" class="btn btn-link">Forgout Password?</a>
  </div>
</form>

{% endblock %}

templates/accounts/recover_password.html
{% extends 'base.html' %}

{% block title %}Forgot Password{% endblock %}

{% block content %}

<div class="page-header">
  <h3>Forgot Password</h3>
</div>

<form action="{{ url_for('accounts_app.recover_password') }}" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.email, with_label=True) }}
  <div class="form-actions">
    <button type="submit" class="btn btn-icon btn-primary">Send</button>
  </div>
</form>

{% endblock %}

templates/accounts/recover_password_confirm.html
{% extends 'base.html' %}

{% block title %}Set new password for login {{ user.username }}{% endblock %}

{% block content %}

<div class="page-header">
  <h3>Set new password for login {{ user.username }}</h3>
</div>

<form action="{{ url_for('accounts_app.recover_password_confirm', token=token) }}" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.password, with_label=True) }}
  {{ form_macro.form_field(form.password_confirm, with_label=True) }}
  <div class="form-actions">
    <button type="submit" class="btn btn-icon btn-primary">Send</button>
  </div>
</form>

{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}

<div class="page-header">
  <h3>Signup</h3>
</div>

<form action="{{ url_for('accounts_app.signup') }}" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.email, with_label=True) }}
  <div class="form-actions">
    <button type="submit" class="btn btn-icon btn-primary">Send</button>
  </div>
</form>

{% endblock %}

templates/accounts/signup_confirm.html
{% extends 'base.html' %}

{% block title %}Confirm Signup{% endblock %}

{% block content %}

<div class="page-header">
  <h3>Confirm Signup</h3>
</div>

<form action="{{ url_for('accounts_app.signup_confirm', token=token) }}" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.name, with_label=True) }}
  {{ form_macro.form_field(form.username, with_label=True) }}
  {{ form_macro.form_field(form.password, with_label=True) }}
  {{ form_macro.form_field(form.password_confirm, with_label=True) }}
  <div class="form-actions">
    <button type="submit" class="btn btn-icon btn-primary">Send</button>
  </div>
</form>

{% endblock %}