accounts/views.py
# -*- coding: utf-8 -*-
from flask import (
    Blueprint, render_template, session, g, flash, request, redirect, url_for,
    current_app
)
from accounts.models import User
from accounts.forms import (
    LoginForm, SignupForm, SignupConfirmForm, RecoverPasswordForm,
    RecoverPasswordConfirmForm
)
from common.utils import get_signer


accounts_app = Blueprint('accounts_app', __name__)


@accounts_app.before_app_request
def load_user():
    g.user = None
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
        except:
            pass


@accounts_app.route('/login/', methods=['GET', 'POST'])
def login():
    next = request.values.get('next', '/')
    form = LoginForm()
    form.next.data = next
    if form.validate_on_submit():
        session['user_id'] = unicode(form.user.pk)
        flash(u'Login successfully', 'success')
        return redirect(next)
    return render_template('accounts/login.html', form=form)


@accounts_app.route('/logout/')
def logout():
    next = request.args.get('next', '/')
    flash(u'Logout successfully', 'success')
    session.pop('user_id', None)
    return redirect(next)


@accounts_app.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        form.save()
        flash(
            u'Check your email to confirm registration.',
            'success'
        )
        return redirect(url_for('pages_app.index'))
    return render_template('accounts/signup.html', form=form)


@accounts_app.route('/signup/<token>/', methods=['GET', 'POST'])
def signup_confirm(token):
    s = get_signer()
    try:
        signed_data = s.loads(
            token, max_age=current_app.config['PROJECT_SIGNUP_TOKEN_MAX_AGE']
        )
        email = signed_data['email']
        signup = signed_data['signup']
    except:
        flash(u'Invalid activation Link.', 'error')
        return redirect(url_for('accounts_app.signup'))

    if User.objects.filter(email=email):
        flash(u'E-mail in use.', 'error')
        return redirect(url_for('accounts_app.signup'))

    next = request.values.get('next', '/')

    form = SignupConfirmForm()
    form.next.data = next
    if form.validate_on_submit():
        user = form.save(email=email)
        session['user_id'] = unicode(user.pk)
        flash(u'Account registered successfully.', 'success')
        return redirect(next)
    return render_template('accounts/signup_confirm.html', form=form, token=token)


@accounts_app.route('/recover-password/', methods=['GET', 'POST'])
def recover_password():
    form = RecoverPasswordForm()
    if form.validate_on_submit():
        form.save()
        flash(
            u'Check it out at your email instructions for setting a new password.',
            'success'
        )
        return redirect(url_for('pages_app.index'))
    return render_template('accounts/recover_password.html', form=form)


@accounts_app.route('/recover-password/<token>/', methods=['GET', 'POST'])
def recover_password_confirm(token):
    s = get_signer()
    try:
        signed_data = s.loads(
            token, max_age=current_app.config['PROJECT_RECOVER_PASSWORD_TOKEN_MAX_AGE']
        )
        email = signed_data['email']
        recover_password = signed_data['recover-password']
    except:
        flash(u'Invalid Link.', 'error')
        return redirect(url_for('pages_app.index'))

    try:
        user = User.objects.get(email=email)
    except:
        flash(u'E-mail not found.', 'error')
        return redirect(url_for('pages_app.index'))

    form = RecoverPasswordConfirmForm()
    form.user = user
    if form.validate_on_submit():
        user = form.save()
        flash(u'Password set successfully.', 'success')
        return redirect(url_for('accounts_app.login'))
    return render_template(
        'accounts/recover_password_confirm.html',
        form=form, token=token, user=user
    )

pages/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template


pages_app = Blueprint('pages_app', __name__)


@pages_app.route('/')
def index():
    return render_template('pages/index.html')


@pages_app.route('/about/')
def about():
    return render_template('pages/about.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %} - Flask Example</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{% block head_description %}{% endblock %}">
  <meta name="author" content="{% block head_author %}{% endblock %}">

  <!-- Le styles -->
  <link href="{{ url_for('static', filename='bootstrap/css/cerulean.css') }}" rel="stylesheet">
  <style>
  body {
    padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
  }
  </style>
  <link href="{{ url_for('static', filename='bootstrap/css/bootstrap-responsive.css') }}" rel="stylesheet">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="{{ url_for('static', filename='bootstrap/js/html5shiv.js') }}"></script>
  <![endif]-->
  {% block extrahead %}{% endblock %}
</head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">

          <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <!-- Be sure to leave the brand out there if you want it shown -->
          <a class="brand" href="/">Flask Example</a>

          <!-- Everything you want hidden at 940px or less, place within here -->
          <div class="nav-collapse collapse">
            <!-- .nav, .navbar-search, .navbar-form, etc -->
            <ul class="nav">
              <li>
                <a href="{{ url_for('pages_app.about') }}">About</a>
              </li>
            </ul>

            {% if g.user %}

            <ul class="nav pull-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  {{ g.user.username }}
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{{ url_for('accounts_app.logout') }}">Logout</a>
                  </li>
                </ul>
              </li>
            </ul>
            
            {% else %}
            
            <ul class="nav pull-right">
              <li>
                <a href="{{ url_for('accounts_app.login') }}">
                  Login
                </a>
              </li>
              <li>
                <a href="{{ url_for('accounts_app.signup') }}">
                  Signup
                </a>
              </li>
            </ul>
            
            {% endif %}
          
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
      <div id="messages">                                                       
        {% for category, message in messages %}                                           
        <div class="alert alert-{{ category }}">                            
          <a class="close" data-dismiss="alert">&times;</a>                     
          <strong>{{ message }}</strong>                                        
        </div>                                                                  
        {% endfor %}                                                            
      </div>
      {% endwith %}

      {% block content %}{% endblock %}
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ url_for('static', filename='js/jquery-1.10.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

templates/form_macro.html
{% macro form_field(field) -%}
    {% set with_label = kwargs.pop('with_label', False) %}
    {% set placeholder = '' %}
    {% if not with_label %}
        {% set placeholder = field.label.text %}
    {% endif %}
    <div class="control-group {% if field.errors %}error{% endif %}">
        {% if with_label %}
            <label for="{{ field.id }}" class="control-label">
                {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
            </label>
        {% endif %}
        <div class="controls">
            {% set class_ = kwargs.pop('class_', '') %}
            {% if field.flags.required %}
                {% set class_ = class_ + ' required' %}
            {% endif %}
            {% if field.type == 'BooleanField' %}
                <label class="checkbox">
                    {{ field(class_=class_, **kwargs) }}
                    {{ field.label.text|safe }}
                </label>
            {% else %}
                {% if field.type in ('TextField', 'TextAreaField', 'PasswordField') %}
                    {% set class_ = class_ + ' input-xlarge' %}
                {% elif field.type == 'FileField' %}
                    {% set class_ = class_ + ' input-file' %}
                {% endif %}
                {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
            {% endif %}
            {% if field.errors %}
                <span class="error help-inline">{{ field.errors|join(', ') }}</span>
            {% endif %}
            {% if field.description %}
                <p class="help-block">{{ field.description|safe }}</p>
            {% endif %}
        </div>
    </div>
{%- endmacro %}

templates/pagination_macro.html
{% macro render_pagination(pagination) %}
  <div class="pagination pagination-large">
    <ul>
  {%- for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
        <li><a href="{{ request.base_url }}?page={{ page }}">{{ page }}</a></li>
      {% else %}
        <li class="active"><a href="#">{{ page }}</a></li>
      {% endif %}
    {% else %}
      <li class="disabled"><span class=ellipsis>…</span></li>
    {% endif %}
  {%- endfor %}
    </ul>
  </div>
{% endmacro %}